version: '3'
services:
    web:
        build:
            context: .
            dockerfile: .docker/node/Dockerfile
        ports:
            - '80:80'
        restart: always
        volumes:
            - .:/web
        depends_on:
            - redis
        env_file:
          - .env
        command:
            "npm run start"

    redis:
        build: .docker/redis
        restart: always
        volumes:
            - .docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - .storage/redis:/data
