#!/usr/bin/env bash

set -e

DIR="$(pwd)"

# Order of docker-compose yaml files
#
# 1) docker-compose.yaml
# 2) docker-compose.override.yaml

source "$DIR/.env"

ARGS=(-f "$DIR/docker-compose.yml")

docker-compose "${ARGS[@]}" "$@"
