#!/usr/bin/env bash

set -e

DIR="$(pwd)"
DOCKER_NAME="web"

source "$DIR/.env"

node_container() {
    ARGS=()

    if [ ! -t 0 ]; then
        ARGS+=(-T)
    fi

    ARGS+=(--user "$(id -u)")

    if ! docker/compose ps | grep "_${DOCKER_NAME}_" | grep "Up" &> /dev/null; then
        docker/compose run --rm --no-deps -p "$PORT:$PORT" "${ARGS[@]}" "$DOCKER_NAME" "$@"

        return
    fi

    docker/compose exec "${ARGS[@]}" "$DOCKER_NAME" "$@";
}

node_container "$@"
